setup:
	@make build
	@make up 
	@make data
build:
	docker compose build 
stop:
	docker compose stop
up:
	docker compose up
data:
	docker exec php_docker -c "php artisan migrate"
	docker exec php_docker bash -c "php artisan db:seed UserSeeder"